### ISSUE TITLE
[Request] Remove props by ClassName

### ISSUE THREAD

**Issue by Aahzmandius** [exectails/Mabioned#4]
When trying to simplify maps, seems I'm often going to be clicking a lot of small props and deleting them one by one. A lot of them aren't tagged with anything useful/unique, so it would be great to be able to remove all props that match a particular ClassName, like the '**scene_prop_13thAnniversary_redrose01**' that are spammed all over Festia.
![image](https://user-images.githubusercontent.com/5201917/41451587-99cfdf26-703b-11e8-995d-c5f8851b01a1.png)

A right-click shortcut for "Remove props like these..." would be great as well.

Oh, and awesome job on the editor 👍

**Comment by exectails** [comment]
Thank you! I hadn't considered a class name filter yet, but it's a good idea. I guess ideally it should support regular expressions, so you can really fine tune what you want to remove. A right-click option is also interesting, and could simply open the filter dialog pre-filled with the class name of the prop.

I will definitely look into this.
